# Generated by Django 6.1.1 on 2026-09-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinattempt',
            name='action',
            field=models.CharField(choices=[('dispense', 'ยืนยันจ่ายยา'), ('void', 'ยกเลิกบิล'), ('adjust', 'ปรับยอดสต็อก')], max_length=20, verbose_name='งาน'),
        ),
    ]
