# Generated by Django 6.1.1 on 2026-09-21 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceLevel',
            fields=[
                ('level', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ระดับ')),
                ('name', models.CharField(max_length=50, verbose_name='ชื่อระดับราคา')),
            ],
            options={
                'verbose_name': 'ระดับราคา',
                'verbose_name_plural': 'ระดับราคา',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=200, verbose_name='ชื่อการค้า')),
                ('generic_name', models.CharField(blank=True, max_length=200, verbose_name='ชื่อสามัญ')),
                ('strength', models.CharField(blank=True, help_text='เช่น 500 mg', max_length=100, verbose_name='ความแรง')),
                ('dosage_form', models.CharField(blank=True, help_text='เช่น เม็ด แคปซูล น้ำเชื่อม', max_length=100, verbose_name='รูปแบบยา')),
                ('registration_no', models.CharField(blank=True, max_length=50, verbose_name='เลขทะเบียนตำรับยา')),
                ('tmt_code', models.CharField(blank=True, max_length=20, verbose_name='รหัส TMT')),
                ('category', models.CharField(choices=[('general', 'สินค้าทั่วไป'), ('household', 'ยาสามัญประจำบ้าน'), ('ready_packed', 'ยาบรรจุเสร็จ (ไม่ใช่ยาอันตราย)'), ('dangerous', 'ยาอันตราย'), ('special_controlled', 'ยาควบคุมพิเศษ')], default='general', max_length=30, verbose_name='ประเภท')),
                ('in_ky11_list', models.BooleanField(default=False, help_text='ยาอันตรายที่ อย. ประกาศให้ทำบัญชีการขาย — ต้องกรอกชื่อผู้ซื้อ', verbose_name='ต้องลงบัญชี ขย.11')),
                ('in_ky13_list', models.BooleanField(default=False, verbose_name='ต้องรายงาน ขย.13')),
                ('base_unit', models.CharField(help_text='หน่วยที่ใช้นับสต็อก เช่น เม็ด แคปซูล ขวด', max_length=30, verbose_name='หน่วยเล็กสุด')),
                ('default_dosage', models.CharField(blank=True, max_length=300, verbose_name='วิธีใช้ (ค่าเริ่มต้นบนฉลาก)')),
                ('label_warning', models.CharField(blank=True, max_length=300, verbose_name='คำเตือนบนฉลาก')),
                ('storage_location', models.CharField(blank=True, max_length=100, verbose_name='ที่เก็บ')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
            ],
            options={
                'verbose_name': 'สินค้า / ยา',
                'verbose_name_plural': 'สินค้า / ยา',
                'ordering': ['trade_name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อผู้ขาย')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='เบอร์โทร')),
                ('license_no', models.CharField(blank=True, max_length=100, verbose_name='เลขที่ใบอนุญาต')),
            ],
            options={
                'verbose_name': 'ผู้ขาย (Supplier)',
                'verbose_name_plural': 'ผู้ขาย (Supplier)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(max_length=50, verbose_name='เลขที่ lot')),
                ('expiry_date', models.DateField(verbose_name='วันหมดอายุ')),
                ('cost_per_base', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='ต้นทุนต่อหน่วยเล็กสุด')),
                ('qty_on_hand', models.IntegerField(default=0, verbose_name='คงเหลือ (หน่วยเล็กสุด)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='รับเข้าครั้งแรก')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lot / วันหมดอายุ',
                'ordering': ['product', 'expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='หน่วย')),
                ('factor', models.PositiveIntegerField(default=1, help_text='1 หน่วยนี้ = กี่หน่วยเล็กสุด', verbose_name='จำนวนหน่วยเล็กสุด')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='บาร์โค้ด')),
                ('is_default', models.BooleanField(default=False, verbose_name='หน่วยขายหลัก')),
                ('price1', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา 1')),
                ('price2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคา 2')),
                ('price3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคา 3')),
                ('price4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคา 4')),
                ('price5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคา 5')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='inventory.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'หน่วยขาย',
                'verbose_name_plural': 'หน่วยขาย',
                'ordering': ['product', 'factor'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_opening_balance', models.BooleanField(default=False, help_text='ใช้ตอนเริ่มใช้ระบบ นับสต็อกที่มีอยู่แล้ว — ไม่ไปลง ขย.9', verbose_name='ยอดยกมา')),
                ('invoice_no', models.CharField(blank=True, max_length=50, verbose_name='เลขที่ใบกำกับ/ใบส่งของ')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='วันที่ในใบกำกับ')),
                ('received_date', models.DateField(verbose_name='วันที่รับยา')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('posted', 'บันทึกเข้าสต็อกแล้ว')], default='draft', max_length=10, verbose_name='สถานะ')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='บันทึกเข้าสต็อกเมื่อ')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.supplier', verbose_name='ผู้ขาย')),
            ],
            options={
                'verbose_name': 'ใบรับยา',
                'verbose_name_plural': 'ใบรับยา',
                'ordering': ['-received_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='จำนวน')),
                ('lot_no', models.CharField(max_length=50, verbose_name='เลขที่ lot')),
                ('expiry_date', models.DateField(verbose_name='วันหมดอายุ')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาทุนต่อหน่วย')),
                ('lot', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.lot')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchase')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.productunit', verbose_name='สินค้า / หน่วย')),
            ],
            options={
                'verbose_name': 'รายการรับยา',
                'verbose_name_plural': 'รายการรับยา',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receive', 'รับเข้า'), ('opening', 'ยอดยกมา'), ('sale', 'ขาย'), ('void', 'ยกเลิกบิล'), ('adjust', 'ปรับยอด')], max_length=20, verbose_name='ประเภท')),
                ('qty', models.IntegerField(verbose_name='จำนวน (หน่วยเล็กสุด)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลา')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ทำรายการ')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.lot', verbose_name='Lot')),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.purchaseitem')),
            ],
            options={
                'verbose_name': 'ความเคลื่อนไหวสต็อก',
                'verbose_name_plural': 'ความเคลื่อนไหวสต็อก',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(fields=('product', 'lot_no', 'expiry_date'), name='unique_lot'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_unit_name_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('barcode',), name='unique_barcode'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.CheckConstraint(condition=models.Q(('factor__gte', 1)), name='unit_factor_positive'),
        ),
    ]
