# Generated by Django 6.1.1 on 2026-09-21 08:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_price_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันหมดอายุ'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='lot_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='เลขที่ lot'),
        ),
    ]
