# Generated by Django 6.1.1 on 2026-09-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_purchase_drafts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ของแถมใส่ 0', max_digits=10, null=True, verbose_name='ราคาทุนต่อหน่วย'),
        ),
    ]
