# Generated by Django 6.1.1 on 2026-09-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_purchase_cost_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อกลุ่มยา/สาร')),
                ('keywords', models.TextField(help_text='ชื่อยาในกลุ่มนี้ คั่นด้วยจุลภาค ไม่สนตัวพิมพ์เล็ก-ใหญ่ เช่น amoxicillin, ampicillin', verbose_name='คำที่ใช้จับคู่')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('related', models.ManyToManyField(blank=True, to='inventory.allergen', verbose_name='อาจแพ้ข้ามกลุ่มกับ')),
            ],
            options={
                'verbose_name': 'กลุ่มยาสำหรับแจ้งเตือนแพ้ยา',
                'verbose_name_plural': 'กลุ่มยาสำหรับแจ้งเตือนแพ้ยา',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.ManyToManyField(blank=True, help_text='ปกติระบบจับคู่จากชื่อสามัญให้เอง เลือกเพิ่มเมื่อชื่อยาไม่บอกกลุ่ม', related_name='products', to='inventory.allergen', verbose_name='กลุ่มยาสำหรับแจ้งเตือนแพ้ยา (เพิ่มเติม)'),
        ),
    ]
