# Generated by Django 6.1.1 on 2026-09-23 15:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_default_allergens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_date', models.DateField(verbose_name='วันที่นับ')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('posted', 'ปรับยอดแล้ว')], default='draft', max_length=10, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='สร้างเมื่อ')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='ปรับยอดเมื่อ')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='เภสัชกรผู้อนุมัติ')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้นับ')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
            ],
            options={
                'verbose_name': 'ใบนับสต็อก / ปรับยอด',
                'verbose_name_plural': 'ใบนับสต็อก / ปรับยอด',
                'ordering': ['-counted_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.IntegerField(verbose_name='ยอดในระบบตอนนับ (หน่วยเล็กสุด)')),
                ('counted_qty', models.IntegerField(blank=True, null=True, verbose_name='นับได้ (หน่วยเล็กสุด)')),
                ('reason', models.CharField(blank=True, choices=[('count', 'นับได้ตามจริง'), ('damaged', 'ชำรุด / แตก / หก'), ('expired', 'หมดอายุ — ทิ้งหรือส่งคืน'), ('lost', 'สูญหาย'), ('other', 'อื่น ๆ (ระบุในหมายเหตุ)')], max_length=20, verbose_name='สาเหตุที่ต่าง')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockcount')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_items', to='inventory.lot', verbose_name='Lot')),
                ('movement', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='count_item', to='inventory.stockmovement')),
            ],
            options={
                'verbose_name': 'รายการนับสต็อก',
                'verbose_name_plural': 'รายการนับสต็อก',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('count', 'lot'), name='unique_lot_per_count')],
            },
        ),
    ]
