# Generated by Django 6.1.1 on 2026-10-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stock_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='รหัสของร้าน หรือรหัสที่ติดมาจากโปรแกรมเดิม — ใช้จับคู่ตอนนำเข้าไฟล์ซ้ำ', max_length=50, verbose_name='รหัสสินค้า'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='unique_product_code'),
        ),
    ]
