# Generated by Django 6.1.1 on 2026-10-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='ติดเองเมื่อนำเข้าจากไฟล์แล้วระบบต้องเดาแทน เช่น ไฟล์ไม่ได้บอกประเภทยา — ปลดเมื่อมีคนเปิดแก้และบันทึก', verbose_name='ยังไม่ได้ตรวจทาน'),
        ),
    ]
