# Generated by Django 6.1.1 on 2026-09-21 05:37

import django.db.models.deletion
import sales.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อ-นามสกุล')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='เบอร์โทร')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('allergies', models.TextField(blank=True, verbose_name='ประวัติแพ้ยา')),
                ('chronic_conditions', models.TextField(blank=True, verbose_name='โรคประจำตัว')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price_level', models.ForeignKey(default=sales.models.default_price_level, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.pricelevel', verbose_name='ระดับราคา')),
            ],
            options={
                'verbose_name': 'ลูกค้า',
                'verbose_name_plural': 'ลูกค้า',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HeldBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='เลขที่บิล')),
                ('client_uuid', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลา')),
                ('buyer_name', models.CharField(blank=True, max_length=200, verbose_name='ชื่อผู้ซื้อ')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ยอดรวม')),
                ('payment_method', models.CharField(choices=[('cash', 'เงินสด'), ('transfer', 'โอน / QR')], max_length=10, verbose_name='ชำระโดย')),
                ('cash_received', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='รับเงิน')),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='เงินทอน')),
                ('is_prescription', models.BooleanField(default=False, verbose_name='ขายตามใบสั่งยา')),
                ('rx_prescriber', models.CharField(blank=True, max_length=200, verbose_name='ผู้สั่งจ่าย')),
                ('rx_prescriber_license', models.CharField(blank=True, max_length=50, verbose_name='เลขที่ใบอนุญาตผู้สั่งจ่าย')),
                ('rx_facility', models.CharField(blank=True, max_length=200, verbose_name='สถานพยาบาล')),
                ('rx_date', models.DateField(blank=True, null=True, verbose_name='วันที่ในใบสั่งยา')),
                ('status', models.CharField(choices=[('completed', 'สำเร็จ'), ('voided', 'ยกเลิก')], default='completed', max_length=10, verbose_name='สถานะ')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='ยกเลิกเมื่อ')),
                ('void_reason', models.CharField(blank=True, max_length=200, verbose_name='เหตุผลที่ยกเลิก')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขาย')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.customer', verbose_name='ลูกค้า')),
                ('price_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.pricelevel', verbose_name='ระดับราคา')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='อนุมัติยกเลิกโดย')),
            ],
            options={
                'verbose_name': 'บิลขาย',
                'verbose_name_plural': 'บิลขาย',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='รายการ')),
                ('unit_name', models.CharField(max_length=30, verbose_name='หน่วย')),
                ('category', models.CharField(choices=[('general', 'สินค้าทั่วไป'), ('household', 'ยาสามัญประจำบ้าน'), ('ready_packed', 'ยาบรรจุเสร็จ (ไม่ใช่ยาอันตราย)'), ('dangerous', 'ยาอันตราย'), ('special_controlled', 'ยาควบคุมพิเศษ')], max_length=30, verbose_name='ประเภท')),
                ('in_ky11_list', models.BooleanField(default=False)),
                ('in_ky13_list', models.BooleanField(default=False)),
                ('qty', models.PositiveIntegerField(verbose_name='จำนวน')),
                ('base_qty', models.PositiveIntegerField(verbose_name='จำนวน (หน่วยเล็กสุด)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='รวม')),
                ('dosage_text', models.CharField(blank=True, max_length=300, verbose_name='วิธีใช้บนฉลาก')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='ยืนยันเมื่อ')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='เภสัชกรผู้ยืนยัน')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.product', verbose_name='สินค้า')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.productunit', verbose_name='หน่วย')),
            ],
            options={
                'verbose_name': 'รายการขาย',
                'verbose_name_plural': 'รายการขาย',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItemLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='จำนวน (หน่วยเล็กสุด)')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.lot')),
                ('movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stockmovement')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.saleitem')),
                ('void_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stockmovement')),
            ],
            options={
                'ordering': ['lot__expiry_date', 'id'],
            },
        ),
    ]
