# Generated by Django 6.1.1 on 2026-09-21 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_default_allergens'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='allergy_alert',
            field=models.TextField(blank=True, verbose_name='แจ้งเตือนแพ้ยา ณ ตอนขาย'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='allergy_note',
            field=models.CharField(blank=True, max_length=300, verbose_name='เหตุผลที่เภสัชกรยังจ่าย'),
        ),
        migrations.CreateModel(
            name='CustomerAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(blank=True, help_text='เช่น Amoxicillin — เลือกกลุ่มยาแล้วเว้นว่างได้', max_length=200, verbose_name='ยาหรือสารที่แพ้')),
                ('reaction', models.CharField(blank=True, max_length=200, verbose_name='อาการ')),
                ('severity', models.CharField(choices=[('unknown', 'ไม่ทราบความรุนแรง'), ('mild', 'ไม่รุนแรง'), ('severe', 'รุนแรง (เช่น SJS หายใจลำบาก ช็อก)')], default='unknown', max_length=10, verbose_name='ความรุนแรง')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='บันทึกเมื่อ')),
                ('allergen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.allergen', verbose_name='กลุ่มยา')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_records', to='sales.customer')),
                ('recorded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
            ],
            options={
                'verbose_name': 'ประวัติแพ้ยา',
                'verbose_name_plural': 'ประวัติแพ้ยา',
                'ordering': ['id'],
            },
        ),
    ]
