# Generated by Django 6.1.1 on 2026-09-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_move_allergy_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='allergies',
        ),
    ]
