from django.conf import settings
from django.db import models

from inventory.models import Lot, PriceLevel, Product, ProductUnit, StockMovement


def default_price_level():
    return 1


class Customer(models.Model):
    name = models.CharField("ชื่อ-นามสกุล", max_length=200)
    phone = models.CharField("เบอร์โทร", max_length=50, blank=True)
    address = models.TextField("ที่อยู่", blank=True)
    price_level = models.ForeignKey(
        PriceLevel, verbose_name="ระดับราคา", default=default_price_level, on_delete=models.PROTECT, related_name="+"
    )
    allergies = models.TextField("ประวัติแพ้ยา", blank=True)
    chronic_conditions = models.TextField("โรคประจำตัว", blank=True)
    note = models.TextField("หมายเหตุ", blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "ลูกค้า"
        verbose_name_plural = "ลูกค้า"
        ordering = ["name"]

    def __str__(self):
        return self.name


class Sale(models.Model):
    class Status(models.TextChoices):
        COMPLETED = "completed", "สำเร็จ"
        VOIDED = "voided", "ยกเลิก"

    class Payment(models.TextChoices):
        CASH = "cash", "เงินสด"
        TRANSFER = "transfer", "โอน / QR"

    number = models.CharField("เลขที่บิล", max_length=20, unique=True)
    # Generated by the counter when the bill starts. Makes checkout safe to retry
    # and ties pharmacist confirmations to this one bill.
    client_uuid = models.UUIDField(unique=True)
    created_at = models.DateTimeField("เวลา", auto_now_add=True)
    cashier = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name="ผู้ขาย", on_delete=models.PROTECT, related_name="+"
    )
    customer = models.ForeignKey(
        Customer, verbose_name="ลูกค้า", null=True, blank=True, on_delete=models.PROTECT, related_name="sales"
    )
    buyer_name = models.CharField("ชื่อผู้ซื้อ", max_length=200, blank=True)
    price_level = models.ForeignKey(PriceLevel, verbose_name="ระดับราคา", on_delete=models.PROTECT, related_name="+")
    total = models.DecimalField("ยอดรวม", max_digits=12, decimal_places=2)
    payment_method = models.CharField("ชำระโดย", max_length=10, choices=Payment.choices)
    cash_received = models.DecimalField("รับเงิน", max_digits=12, decimal_places=2, null=True, blank=True)
    change = models.DecimalField("เงินทอน", max_digits=12, decimal_places=2, null=True, blank=True)
    is_prescription = models.BooleanField("ขายตามใบสั่งยา", default=False)
    rx_prescriber = models.CharField("ผู้สั่งจ่าย", max_length=200, blank=True)
    rx_prescriber_license = models.CharField("เลขที่ใบอนุญาตผู้สั่งจ่าย", max_length=50, blank=True)
    rx_facility = models.CharField("สถานพยาบาล", max_length=200, blank=True)
    rx_date = models.DateField("วันที่ในใบสั่งยา", null=True, blank=True)
    status = models.CharField("สถานะ", max_length=10, choices=Status.choices, default=Status.COMPLETED)
    voided_at = models.DateTimeField("ยกเลิกเมื่อ", null=True, blank=True)
    voided_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name="อนุมัติยกเลิกโดย", null=True, blank=True,
        on_delete=models.PROTECT, related_name="+",
    )
    void_reason = models.CharField("เหตุผลที่ยกเลิก", max_length=200, blank=True)

    class Meta:
        verbose_name = "บิลขาย"
        verbose_name_plural = "บิลขาย"
        ordering = ["-created_at", "-id"]

    def __str__(self):
        return self.number

    @property
    def buyer_display(self) -> str:
        return self.buyer_name or (self.customer.name if self.customer else "")


class SaleItem(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE, related_name="items")
    product = models.ForeignKey(Product, verbose_name="สินค้า", on_delete=models.PROTECT, related_name="+")
    unit = models.ForeignKey(ProductUnit, verbose_name="หน่วย", on_delete=models.PROTECT, related_name="+")
    # Snapshots: what was true at the time of sale, even if the product changes later.
    description = models.CharField("รายการ", max_length=300)
    unit_name = models.CharField("หน่วย", max_length=30)
    category = models.CharField("ประเภท", max_length=30, choices=Product.Category.choices)
    in_ky11_list = models.BooleanField(default=False)
    in_ky13_list = models.BooleanField(default=False)
    qty = models.PositiveIntegerField("จำนวน")
    base_qty = models.PositiveIntegerField("จำนวน (หน่วยเล็กสุด)")
    unit_price = models.DecimalField("ราคาต่อหน่วย", max_digits=10, decimal_places=2)
    line_total = models.DecimalField("รวม", max_digits=12, decimal_places=2)
    dosage_text = models.CharField("วิธีใช้บนฉลาก", max_length=300, blank=True)
    confirmed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name="เภสัชกรผู้ยืนยัน", null=True, blank=True,
        on_delete=models.PROTECT, related_name="+",
    )
    confirmed_at = models.DateTimeField("ยืนยันเมื่อ", null=True, blank=True)

    class Meta:
        verbose_name = "รายการขาย"
        verbose_name_plural = "รายการขาย"
        ordering = ["id"]


class SaleItemLot(models.Model):
    """Which lots one sale line was taken from — a line can span several lots."""

    sale_item = models.ForeignKey(SaleItem, on_delete=models.CASCADE, related_name="allocations")
    lot = models.ForeignKey(Lot, on_delete=models.PROTECT, related_name="+")
    qty = models.PositiveIntegerField("จำนวน (หน่วยเล็กสุด)")
    movement = models.OneToOneField(StockMovement, on_delete=models.PROTECT, related_name="+")
    void_movement = models.OneToOneField(
        StockMovement, null=True, blank=True, on_delete=models.PROTECT, related_name="+"
    )

    class Meta:
        ordering = ["lot__expiry_date", "id"]


class HeldBill(models.Model):
    """บิลที่พักไว้ (F10) เช่น รอเภสัชกร หรือลูกค้ายังเลือกไม่เสร็จ"""

    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="+")
    label = models.CharField(max_length=200, blank=True)
    payload = models.JSONField()

    class Meta:
        ordering = ["created_at"]
