# Generated by Django 6.1.1 on 2026-09-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ร้านยา', max_length=200, verbose_name='ชื่อร้าน')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='เบอร์โทร')),
                ('license_no', models.CharField(blank=True, max_length=100, verbose_name='เลขที่ใบอนุญาตขายยา')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='เลขประจำตัวผู้เสียภาษี')),
                ('promptpay_id', models.CharField(blank=True, help_text='ถ้าว่างไว้ หน้ารับเงินโอนจะไม่แสดง QR', max_length=20, verbose_name='พร้อมเพย์ (เบอร์มือถือหรือเลขประจำตัวผู้เสียภาษี)')),
                ('receipt_footer', models.CharField(blank=True, max_length=200, verbose_name='ข้อความท้ายใบเสร็จ')),
                ('near_expiry_days', models.PositiveIntegerField(default=180, verbose_name='เตือนยาใกล้หมดอายุล่วงหน้า (วัน)')),
            ],
            options={
                'verbose_name': 'ข้อมูลร้าน',
                'verbose_name_plural': 'ข้อมูลร้าน',
            },
        ),
    ]
